# Generated by Django 5.2.4 on 2025-11-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='preferred_mode',
            field=models.CharField(default='philosophical', max_length=30),
        ),
    ]
