# Generated by Django 5.2.4 on 2025-07-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_entry', models.TextField()),
                ('midday_entry', models.TextField(blank=True)),
                ('end_entry', models.TextField(blank=True)),
            ],
        ),
    ]
