# Generated by Django 5.2.4 on 2025-07-16 07:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
