# Generated by Django 5.2.4 on 2025-07-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journalmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journalmode'),
        ),
    ]
