# Generated by Django 5.2.4 on 2025-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_journalentry_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmode',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
