# Generated by Django 5.2.4 on 2025-08-02 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_journalmode_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content_type', models.CharField(choices=[('global', 'Global'), ('zodiac', 'Zodiac-specific'), ('personalized', 'User-personalized')], default='global', max_length=20)),
                ('personalization_key', models.CharField(blank=True, max_length=100, null=True)),
                ('content_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journalmode')),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'date', 'content_type'], name='journal_dai_mode_id_93ae62_idx')],
                'unique_together': {('mode', 'date', 'content_type', 'personalization_key')},
            },
        ),
    ]
