# Generated by Django 5.2.4 on 2025-08-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_dailycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='tags',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='journal.tag'),
        ),
    ]
