# Generated by Django 5.2.4 on 2025-09-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_tag_remove_journalentry_tags_journalentry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
