# Generated by Django 5.2.4 on 2025-09-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_tag_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='mode',
        ),
    ]
