# Generated by Django 5.2.4 on 2025-09-11 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_remove_journalentry_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
