# Generated by Django 5.2.4 on 2025-09-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_journalentry_created_at'),
        ('userprofile', '0004_alter_userprofile_preferred_mode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyContent',
        ),
        migrations.DeleteModel(
            name='JournalMode',
        ),
    ]
