# Generated by Django 5.2.4 on 2025-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_delete_dailycontent_delete_journalmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Sentiment score from -1.0 (very negative) to 1.0 (very positive)'),
        ),
    ]
