# Generated by Django 5.2.4 on 2026-01-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_tag_sentiment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlanetarySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('planetary_data', models.JSONField(help_text='Complete planetary positions from AstrologyService')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'timezone'], name='journal_dai_date_4f3ed3_idx')],
                'unique_together': {('date', 'timezone')},
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='planetary_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journal.dailyplanetarysnapshot'),
        ),
    ]
