# Generated by Django 5.2.4 on 2026-01-24 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_dailyplanetarysnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCosmicCoincidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_key', models.CharField(max_length=20)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidences', to='journal.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmic_indices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'planet_key'], name='journal_jou_user_id_a50dcf_idx')],
                'unique_together': {('entry', 'planet_key')},
            },
        ),
    ]
