# Generated by Django 5.2.4 on 2025-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_instant_commentary',
            field=models.BooleanField(default=True, help_text='Show AI-generated commentary immediately after creating journal entries', verbose_name='Enable Instant AI Insights'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_commentary_date',
            field=models.DateField(blank=True, help_text='Date when the last AI insight was shown', null=True, verbose_name='Last Insight Date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_daily_commentaries',
            field=models.IntegerField(default=3, help_text='Maximum number of AI insights to show per day', verbose_name='Max Daily Insights'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_words_for_commentary',
            field=models.IntegerField(default=30, help_text='Entries must have at least this many words to trigger AI insights', verbose_name='Minimum Words for Insights'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='today_commentary_count',
            field=models.IntegerField(default=0, help_text='Number of AI insights shown today (resets daily)', verbose_name="Today's Insight Count"),
        ),
    ]
