# Generated by Django 5.2.4 on 2025-09-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_enable_instant_commentary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text="User's date of birth (used for natal chart calculations)", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Birthplace (optional, can be linked with coordinates later)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_time',
            field=models.TimeField(blank=True, help_text="User's time of birth (optional, used for more precise natal charts)", null=True),
        ),
    ]
