# Generated by Django 5.2.4 on 2025-09-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0001_initial'),
        ('userprofile', '0003_userprofile_birth_date_userprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modes.mode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='modes.mode'),
        ),
    ]
