# Generated by Django 5.2.4 on 2025-10-01 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_preferred_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(help_text='Date of birth (required)')),
                ('birth_time', models.TimeField(blank=True, help_text='Exact time of birth (optional - affects house calculations)', null=True)),
                ('birth_latitude', models.DecimalField(decimal_places=6, help_text='Birth location latitude (-90 to 90)', max_digits=9)),
                ('birth_longitude', models.DecimalField(decimal_places=6, help_text='Birth location longitude (-180 to 180)', max_digits=9)),
                ('birth_timezone', models.CharField(default='UTC', help_text="IANA timezone (e.g., 'Asia/Manila', 'America/New_York')", max_length=50)),
                ('birth_city', models.CharField(blank=True, help_text='City name for display', max_length=100)),
                ('birth_country', models.CharField(blank=True, help_text='Country name for display', max_length=100)),
                ('has_birth_time', models.BooleanField(default=False, help_text='Flag indicating if exact birth time is known')),
                ('cached_chart_data', models.JSONField(blank=True, help_text='Cached natal chart calculation (JSON)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birth Profile',
                'verbose_name_plural': 'Birth Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
