# Generated by Django 5.2.4 on 2025-10-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_birthprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_time',
        ),
    ]
