# Generated by Django 5.2.4 on 2025-11-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0001_initial'),
        ('userprofile', '0006_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_mode',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modes.mode'),
        ),
    ]
