import json
from django.core.management.base import BaseCommand
from django.core import serializers
from django.apps import apps
from userprofile.signals import disable_signals, enable_signals
from user_management.signals import disable_signals as ds, enable_signals as es
from pathlib import Path


class Command(BaseCommand):
    help = 'Load data while excluding ContentTypes and controlling signal management'

    # Models to exclude (auto-generated by migrations)
    EXCLUDE_MODELS = {
        'contenttypes.contenttype',
        'auth.permission',
        'admin.logentry',
        'sessions.session',
    }

    def handle(self, *args, **kwargs):
        file_path = Path("db_dump_02-11-26_prod.json")

        # Step 1 — Validate and fix encoding issues
        try:
            with open(file_path, "rb") as f:
                raw_data = f.read()
            decoded_data = raw_data.decode("utf-8")  # Will fail if not pure UTF-8

        except UnicodeDecodeError as e:
            self.stderr.write(self.style.WARNING(f"Encoding issue detected: {e}"))
            # Attempt to fix (replace invalid chars with closest match)
            decoded_data = raw_data.decode("utf-8", errors="replace")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(decoded_data)
            self.stdout.write(self.style.WARNING("Invalid characters replaced."))

        # Step 2 — Ensure JSON is valid and filter out excluded models
        try:
            data = json.loads(decoded_data)

            # Count original objects
            original_count = len(data)

            # Filter out excluded models
            filtered_data = []
            excluded_count = 0

            for obj in data:
                model_label = obj.get('model', '').lower()
                if model_label not in self.EXCLUDE_MODELS:
                    filtered_data.append(obj)
                else:
                    excluded_count += 1

            self.stdout.write(
                self.style.WARNING(
                    f"📊 Filtering: {original_count} total objects, "
                    f"excluding {excluded_count} system objects, "
                    f"loading {len(filtered_data)} objects"
                )
            )

            # Show what was excluded
            if excluded_count > 0:
                excluded_models_found = set()
                for obj in data:
                    model_label = obj.get('model', '').lower()
                    if model_label in self.EXCLUDE_MODELS:
                        excluded_models_found.add(model_label)

                self.stdout.write(self.style.WARNING("🚫 Excluded models:"))
                for model in excluded_models_found:
                    self.stdout.write(f"   - {model}")

        except json.JSONDecodeError as e:
            self.stderr.write(self.style.ERROR(f"JSON is invalid: {e}"))
            return

        # Step 3 — Temporarily disable signals
        self.stdout.write("🔇 Disabling signals...")
        disable_signals()
        ds()

        try:
            # Step 4 — Deserialize and save filtered objects
            self.stdout.write("📥 Loading data...")

            # Convert back to JSON string for deserializer
            filtered_json = json.dumps(filtered_data)

            # Deserialize objects
            objects_to_save = []
            for obj in serializers.deserialize('json', filtered_json):
                objects_to_save.append(obj)

            # Bulk save
            saved_count = 0
            errors = []

            for obj in objects_to_save:
                try:
                    obj.save()
                    saved_count += 1
                except Exception as e:
                    model_name = f"{obj.object._meta.app_label}.{obj.object._meta.model_name}"
                    error_msg = f"{model_name} (pk={obj.object.pk}): {str(e)}"
                    errors.append(error_msg)

            # Report results
            self.stdout.write(
                self.style.SUCCESS(f"✅ Successfully loaded {saved_count} objects")
            )

            if errors:
                self.stdout.write(
                    self.style.WARNING(f"⚠️  {len(errors)} objects failed to load:")
                )
                for error in errors[:10]:  # Show first 10 errors
                    self.stdout.write(f"   - {error}")
                if len(errors) > 10:
                    self.stdout.write(f"   ... and {len(errors) - 10} more errors")

        except Exception as e:
            self.stderr.write(self.style.ERROR(f"Error loading data: {e}"))
            import traceback
            self.stderr.write(traceback.format_exc())

        finally:
            # Step 5 — Re-enable signals (always runs)
            self.stdout.write("🔊 Re-enabling signals...")
            enable_signals()
            es()

        # Step 6 — Reset database sequences (CRITICAL!)
        self.stdout.write("🔄 Resetting database sequences...")
        from django.db import connection, transaction

        # Force commit any pending transactions first
        transaction.commit()

        sequences_reset = 0

        with connection.cursor() as cursor:
            # Query sequences directly - most reliable method
            cursor.execute("""
                SELECT sequencename 
                FROM pg_sequences 
                WHERE schemaname = 'public'
            """)

            sequences = [row[0] for row in cursor.fetchall()]
            self.stdout.write(f"   Found {len(sequences)} sequences to reset")

            for seq_name in sequences:
                try:
                    # Parse table and column name from sequence
                    # Pattern: tablename_columnname_seq
                    if seq_name.endswith('_seq'):
                        # Remove _seq suffix
                        base_name = seq_name[:-4]
                        # Split on last underscore to get column name
                        last_underscore = base_name.rfind('_')
                        if last_underscore > 0:
                            table_name = base_name[:last_underscore]
                            column_name = base_name[last_underscore + 1:]
                        else:
                            # No underscore found, assume whole thing is table and column is 'id'
                            table_name = base_name
                            column_name = 'id'
                    else:
                        continue

                    # Reset the sequence to MAX(column) + 1
                    cursor.execute(f"""
                        SELECT setval(
                            '{seq_name}', 
                            (SELECT COALESCE(MAX({column_name}), 0) + 1 FROM {table_name})
                        )
                    """)
                    result = cursor.fetchone()

                    if result and result[0]:
                        sequences_reset += 1
                        self.stdout.write(f"   ✓ {table_name}.{column_name} → next: {result[0]}")

                except Exception as e:
                    self.stdout.write(self.style.WARNING(f"   ⚠ {seq_name}: {e}"))

            # Commit all sequence changes
            transaction.commit()

        self.stdout.write(self.style.SUCCESS(f"✅ Reset {sequences_reset} sequences and committed"))
        self.stdout.write(self.style.SUCCESS("🎉 Load process completed!"))