# Generated by Django 5.2.4 on 2025-10-10 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('daily_overview', 'Daily Overview'), ('transit_focus', 'Transit Focus'), ('element_wisdom', 'Element Wisdom')], help_text='Type of astrological reading', max_length=50)),
                ('reading_text', models.TextField(help_text='AI-generated reading content')),
                ('transits_analyzed', models.IntegerField(default=0, help_text='Number of transits analyzed in this reading')),
                ('top_transits', models.JSONField(default=list, help_text='Top 3 transits for reference (JSON)')),
                ('moon_phase', models.CharField(blank=True, help_text='Moon phase at time of reading', max_length=50)),
                ('cosmic_weather', models.TextField(blank=True, help_text='General cosmic conditions')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='When this reading was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When record was first created')),
                ('user', models.OneToOneField(help_text='One reading per user - updates replace old reading', on_delete=django.db.models.deletion.CASCADE, related_name='current_ai_reading', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Reading',
                'verbose_name_plural': 'AI Readings',
                'ordering': ['-generated_at'],
            },
        ),
    ]
