# Generated by Django 5.2.4 on 2025-10-14 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_dive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireading',
            name='user',
            field=models.ForeignKey(help_text='User who owns this reading', on_delete=django.db.models.deletion.CASCADE, related_name='ai_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
