# Generated by Django 5.2.4 on 2025-10-14 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_dive', '0002_alter_aireading_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aireading',
            options={'verbose_name': 'AI Reading Collection', 'verbose_name_plural': 'AI Reading Collections'},
        ),
        migrations.RemoveField(
            model_name='aireading',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='aireading',
            name='moon_phase',
        ),
        migrations.RemoveField(
            model_name='aireading',
            name='reading_text',
        ),
        migrations.RemoveField(
            model_name='aireading',
            name='reading_type',
        ),
        migrations.RemoveField(
            model_name='aireading',
            name='top_transits',
        ),
        migrations.RemoveField(
            model_name='aireading',
            name='transits_analyzed',
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_generated_at',
            field=models.DateTimeField(blank=True, help_text='When daily overview was generated', null=True),
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_moon_phase',
            field=models.CharField(blank=True, help_text='Moon phase during daily overview', max_length=50),
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_text',
            field=models.TextField(blank=True, help_text='Daily overview reading content'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_transits',
            field=models.JSONField(default=list, help_text='Top transits for daily overview'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_generated_at',
            field=models.DateTimeField(blank=True, help_text='When element wisdom was generated', null=True),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_moon_phase',
            field=models.CharField(blank=True, help_text='Moon phase during element wisdom', max_length=50),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_text',
            field=models.TextField(blank=True, help_text='Element wisdom reading content'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_transits',
            field=models.JSONField(default=list, help_text='Top transits for element wisdom'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='transit_focus_generated_at',
            field=models.DateTimeField(blank=True, help_text='When transit focus was generated', null=True),
        ),
        migrations.AddField(
            model_name='aireading',
            name='transit_focus_moon_phase',
            field=models.CharField(blank=True, help_text='Moon phase during transit focus', max_length=50),
        ),
        migrations.AddField(
            model_name='aireading',
            name='transit_focus_text',
            field=models.TextField(blank=True, help_text='Transit focus reading content'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='transit_focus_transits',
            field=models.JSONField(default=list, help_text='Top transits for transit focus'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update to any reading'),
        ),
        migrations.AlterField(
            model_name='aireading',
            name='user',
            field=models.OneToOneField(help_text='User who owns these readings', on_delete=django.db.models.deletion.CASCADE, related_name='ai_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
