# Generated by Django 5.2.4 on 2025-11-07 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_dive', '0003_alter_aireading_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCardDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=5)),
                ('keywords', models.CharField(max_length=200)),
                ('interpretation', models.TextField()),
                ('astro_context', models.TextField(blank=True)),
                ('natal_insight', models.TextField(blank=True)),
                ('drawn_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarot_draws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-drawn_at'],
            },
        ),
    ]
