# Generated by Django 5.2.4 on 2025-12-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_dive', '0004_tarotcarddraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_transit_summaries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_transit_summaries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aireading',
            name='transit_focus_transit_summaries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
