# Generated by Django 5.2.4 on 2025-12-20 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_dive', '0005_aireading_daily_overview_transit_summaries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireading',
            name='daily_overview_transit_summaries',
        ),
        migrations.RemoveField(
            model_name='aireading',
            name='element_wisdom_transit_summaries',
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_cosmic_weather',
            field=models.TextField(blank=True, help_text='Cosmic weather description'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_element_dist',
            field=models.JSONField(blank=True, default=dict, help_text='Element distribution in current sky'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_modality_dist',
            field=models.JSONField(blank=True, default=dict, help_text='Modality distribution'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_sign_concentrations',
            field=models.JSONField(blank=True, default=list, help_text='Signs with multiple planets'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='daily_overview_sky_conjunctions',
            field=models.JSONField(blank=True, default=list, help_text='Current planetary conjunctions in sky'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_comparison',
            field=models.JSONField(blank=True, default=dict, help_text='Comparison between natal and current elements'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_current_elements',
            field=models.JSONField(blank=True, default=dict, help_text='Current sky element distribution and analysis'),
        ),
        migrations.AddField(
            model_name='aireading',
            name='element_wisdom_natal_elements',
            field=models.JSONField(blank=True, default=dict, help_text='Natal chart element distribution'),
        ),
        migrations.AlterField(
            model_name='aireading',
            name='cosmic_weather',
            field=models.TextField(blank=True, help_text='General cosmic conditions description'),
        ),
        migrations.AlterField(
            model_name='aireading',
            name='daily_overview_moon_phase',
            field=models.JSONField(blank=True, default=dict, help_text='Moon phase data (phase, emoji, illumination, description)'),
        ),
        migrations.AlterField(
            model_name='aireading',
            name='element_wisdom_moon_phase',
            field=models.JSONField(blank=True, default=dict, help_text='Moon phase data (minimal)'),
        ),
        migrations.AlterField(
            model_name='aireading',
            name='element_wisdom_transits',
            field=models.JSONField(default=list, help_text="Empty list - element wisdom doesn't use transits"),
        ),
        migrations.AlterField(
            model_name='aireading',
            name='transit_focus_moon_phase',
            field=models.CharField(blank=True, help_text='Moon phase name only', max_length=100),
        ),
        migrations.AlterField(
            model_name='aireading',
            name='transit_focus_transit_summaries',
            field=models.JSONField(blank=True, default=list, help_text='Full transit interpretations with psychological depth'),
        ),
        migrations.AddIndex(
            model_name='aireading',
            index=models.Index(fields=['-daily_overview_generated_at'], name='deep_dive_a_daily_o_8f99e6_idx'),
        ),
        migrations.AddIndex(
            model_name='aireading',
            index=models.Index(fields=['-transit_focus_generated_at'], name='deep_dive_a_transit_86b2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='aireading',
            index=models.Index(fields=['-element_wisdom_generated_at'], name='deep_dive_a_element_3d99fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tarotcarddraw',
            index=models.Index(fields=['-drawn_at'], name='deep_dive_t_drawn_a_060375_idx'),
        ),
        migrations.AddIndex(
            model_name='tarotcarddraw',
            index=models.Index(fields=['user', '-drawn_at'], name='deep_dive_t_user_id_b19de9_idx'),
        ),
    ]
