# Generated by Django 5.2.4 on 2026-01-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_tag_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='planetary_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of all planetary positions when entry was created', null=True),
        ),
    ]
