# Generated by Django 5.2.4 on 2025-09-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content_type', models.CharField(choices=[('global', 'Global'), ('zodiac', 'Zodiac-specific'), ('personalized', 'User-personalized')], default='global', max_length=20)),
                ('personalization_key', models.CharField(blank=True, max_length=100, null=True)),
                ('content_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modes.mode')),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'date', 'content_type'], name='modes_daily_mode_id_b29c49_idx')],
                'unique_together': {('mode', 'date', 'content_type', 'personalization_key')},
            },
        ),
    ]
